#!/bin/bash -e
#
# Generates EOO detection/false-trigger data for the V2 test report, using
# tx2.py -> ch -> rx2.py (see eoo_detect_prob.sh/eoo_false_prob.sh). Writes
# a LaTeX table (tab:eoo_p_detect equivalent) plus a false-trigger summary
# to a .tex file for direct inclusion in the report.
#
# This is a rough re-calibration against the old (--EbNodB-based) table --
# the --No values below aren't chosen to hit the old table's SNR points
# precisely, just to give a similar spread from clean to poor. The real
# numbers may differ noticeably from the old table now that the channel
# genuinely fades/filters the EOO segment (see Issue#1) -- that's expected
# and is the point of this re-run, not a bug.
#
# Usage:
#   ./test/eoo_report_data.sh [--N <trials>] [--out <file.tex>]

N=20
out=doc/v2_test_report_eoo.tex

function print_help {
    echo
    echo "Generate EOO detection/false-trigger data for the V2 test report"
    echo
    echo "  usage: ./test/eoo_report_data.sh [--N trials] [--out file.tex]"
    echo
    exit
}

while [[ $# -gt 0 ]]; do
    case $1 in
        --N)   N=$2;   shift 2 ;;
        --out) out=$2; shift 2 ;;
        -h|--help) print_help ;;
        *) echo "Unknown argument: $1"; print_help ;;
    esac
done

# AWGN and MPP No sweeps: clean, then three points spanning the knee region
# (picked from quick single-trial calibration checks, not precisely matched
# to the old table's EbNodB-based SNR points).
awgn_Nos="-100 -20 -22 -24"
mpp_Nos="-100 -22 -25 -28"

detect_log=$(mktemp)
false_log=$(mktemp)
trap "rm -f $detect_log $false_log" EXIT

echo "Running EOO detection probability sweep (N=$N per point)..."
> $detect_log
for No in $awgn_Nos; do
    echo "  AWGN No=$No"
    ./test/eoo_detect_prob.sh --No $No --channel awgn --N $N 2>/dev/null | grep "Result:" | \
        sed "s/^/AWGN $No: /" >> $detect_log
done
for No in $mpp_Nos; do
    echo "  MPP No=$No"
    ./test/eoo_detect_prob.sh --No $No --channel mpp --N $N 2>/dev/null | grep "Result:" | \
        sed "s/^/MPP $No: /" >> $detect_log
done

echo "Running EOO false-trigger sweep (N=$N per point)..."
> $false_log
echo "  AWGN No=-24" && ./test/eoo_false_prob.sh --No -24 --channel awgn --N $N 2>/dev/null | \
    grep -E "Mean SNR3k|Result:" | sed "s/^/AWGN -24: /" >> $false_log
echo "  MPP No=-25" && ./test/eoo_false_prob.sh --No -25 --channel mpp --N $N 2>/dev/null | \
    grep -E "Mean SNR3k|Result:" | sed "s/^/MPP -25: /" >> $false_log

# Parse "CHANNEL No: Result: D/N detected, P(detect) = P, mean SNR3k = SdB"
python3 -c "
import re

rows = []
with open('$detect_log') as f:
    for line in f:
        m = re.match(r'(\w+) (-?\d+): Result: (\d+)/(\d+) detected, P\(detect\) = ([\d.]+), mean SNR3k = (-?[\d.]+)dB', line)
        if m:
            chan, No, d, n, p, snr = m.groups()
            rows.append((chan, No, float(snr), float(p)))
rows.sort(key=lambda r: (r[0], -r[2]))  # group by channel, descending SNR within each

with open('$out', 'w') as f:
    f.write('%% Auto-generated by test/eoo_report_data.sh -- N=$N trials per point\n')
    f.write('%% tx2.py -> ch -> rx2.py, both data and EOO genuinely faded/filtered (see Issue #1)\n')
    f.write('\\\\begin{table} [h]\n')
    f.write(f'\\\\caption{{End of Over Probability of Detection over \$N={$N}\$ trials}}\n')
    f.write('\\\\label{tab:eoo_p_detect}\n')
    f.write('\\\\centering\n')
    f.write('\\\\begin{tabular}{ c | r | r }\n')
    f.write(' \\\\hline\n')
    f.write(' Channel & SNR3k (\\\\si{dB}) & P(detect) \\\\\\\\\n')
    f.write(' \\\\hline\n')
    for chan, No, snr, p in rows:
        f.write(f' {chan} & {snr:.1f} & {p:.2f} \\\\\\\\\n')
    f.write(' \\\\hline\n')
    f.write('\\\\end{tabular}\n')
    f.write('\\\\end{table}\n\n')

    f.write('%% False-trigger results\n')
    with open('$false_log') as flog:
        f.write('%% ' + flog.read().replace(chr(10), chr(10)+'%% '))
print(f'Wrote {\"$out\"}')"

cat $detect_log
echo
cat $false_log
