#!/bin/bash
#
# Compare models by plotting loss v SNR/PSNR curves from data generated by inference.py
# Similar to compare_models.sh, but uses time domain path in forward() that is closer to the
# real world configuration, e.g. time domain multipath model, cyclic prefix, ISI, pilot 
# insertion and DSP EQ (if used).

# Build an input test file from Librispeech
function build_input_file_from_librispeech() {
  n_samples=$1
  input_file=$2
  source=~/.cache/LibriSpeech/test-clean
  if [ ! -d $source ]; then
    echo "cant find Librispeech source directory" $source
    exit 1 
  fi
  flac=$(find ${source} -name '*.flac')
  # randomise selection of files so we don't get them all from one speaker,
  # --random-source makes it the same repeatable random sequence so we get the 
  # same results on each run
  flac=$(echo "$flac" | shuf --random-source=<(yes 42) | head -n $n_samples)
  n=$(echo "$flac" | wc -l)
  printf "Collecting %d samples from Librispeech\n" $n
  sox ${flac} -c 1 -r 16000 ${input_file}
  dur=$(sox --info -D ${input_file})
  printf "%s duration %f\n" $input_file $dur
}

# Run inference on a range of SNRs to compute loss
function run_model() {
  model=$1
  dim=$2
  epoch=$3
  chan=$4
  freq_offset=$5
  shift
  shift
  shift
  shift
  shift
  EbNodB_list='0 1.5 3 4.5 6 9 12 15 18 21 24'
  results=${model}_${chan}_${freq_offset}Hz_loss_SNR3k.txt
  
  # return if results file already exists
  if [ $rebuild -eq 0 ]; then
    if [ -f $results ]; then
      return
    fi
  fi
  
  rm -f $results
  for aEbNodB in $EbNodB_list
    do
      log=$(./inference.sh ${model}/checkpoints/checkpoint_epoch_${epoch}.pth ${input_file} /dev/null --bottleneck 3 --rate_Fs \
            --latent-dim ${dim} $@ --EbNodB ${aEbNodB} --freq_offset ${freq_offset}) 
      SNR3k=$(echo "$log" | grep "Measured:" | tr -s ' ' | cut -d' ' -f4)
      PAPR=$(echo "$log" | grep "Measured:" | tr -s ' ' | cut -d' ' -f5)
      loss=$(echo "$log" | grep "loss:" | tr -s ' ' | cut -d' ' -f2)
      printf "%f\t%f\t%f\n" $SNR3k $loss $PAPR >> $results
    done
}

# Run inference + rx2.sh on a range of SNRs to compute loss
function run_model_rx2() {
  model=$1
  model_ft=$2
  model_sync=$3
  dim=$4
  epoch=$5
  chan=$6
  shift
  shift
  shift
  shift
  shift
  shift
  # EbNodB_list='0 1.5 3 4.5 6 9 12 15 18 21 24'
  EbNodB_list='1 3 6 9 12 18 24'
  results=${model}_${chan}_loss_SNR3k.txt
  
  # return if results file already exists
  if [ $rebuild -eq 0 ]; then
    if [ -f $results ]; then
      return
    fi
  fi

  rx=$(mktemp)
  rm -f $results
  for aEbNodB in $EbNodB_list
    do
      log=$(./inference.sh ${model}/checkpoints/checkpoint_epoch_${epoch}.pth ${input_file} /dev/null --rate_Fs \
						   --latent-dim ${dim} --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata \
						   --w1_dec 128 --write_rx ${rx} --EbNodB ${aEbNodB} $@)
      SNR3k=$(echo "$log" | grep "Measured:" | tr -s ' ' | cut -d' ' -f4)
      PAPR=$(echo "$log" | grep "Measured:" | tr -s ' ' | cut -d' ' -f5)
      loss_inf=$(echo "$log" | grep "loss:" | tr -s ' ' | cut -d' ' -f2)
    ./jmv_ft_tool.sh ${rx} delta_hat.f32
    # note ${model_ft} ${model_sync} not actually used in practice, we just valid models to run previous code
	  ./rx2.sh ${model}/checkpoints/checkpoint_epoch_${epoch}.pth ${model_ft} ${model_sync} \
               ${rx} /dev/null --latent-dim 56 --w1_dec 128 --noframe_sync --read_delta_hat delta_hat.f32
	  loss_rx2=$(python3 loss.py features_in.f32 features_out_rx2.f32 --clip_start 25 | grep 'loss' | tr -s ' ' | cut -d' ' -f3)
      printf "%f\t%f\t%f\t%f\n" $SNR3k $loss_rx2 $PAPR $loss_inf >> $results
    done
}

function print_help {
    echo
    echo " Compare models by plotting loss v SNR/PSNR curves from time domain inference"
    echo
    echo "  usage ./compare_models_inf.sh [-n NumberSpeechSamples] [-p plotName] [-r]"
    echo
    echo "    -n NumberSpeechSamples    Use a low number (e.g. 10) when testing plots"
    echo "    -p                        Name of plot (see source)"
    echo "    -r                        Rebuild results files even if they already exists (e.g. if -n has changed)"
    echo
    exit
}

# default is about 10 minutes long
n_samples=80
input_file="wav/librispeech.wav"
plot="250413_inf"
rebuild=0

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -n)
        n_samples="$2"	
        shift
        shift
    ;;
    -p)
        plot="$2"	
        shift
        shift
    ;;
    -r)
        rebuild=1	
        shift
    ;;
    -h)
        print_help	
    ;;
    *)
    POSITIONAL+=("$1") # save it in an array for later
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

build_input_file_from_librispeech ${n_samples} ${input_file}


# compare RADE V1 to 250227b
if [ $plot == "250227b_inf" ]; then
  #run_model model19_check3 80 100 awgn --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  #run_model model19_check3 80 100 mpp --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  #run_model 250227b_test 40 200 awgn --cp 0.004 --time_offset -16 --correct_time_offset -32 
  #run_model 250227b_test 40 200 mpp --cp 0.004 --time_offset -16 --correct_time_offset -32 --g_file g_mpp.f32

  model_list='model19_check3_awgn model19_check3_mpp 250227b_test_awgn 250227b_test_mpp'
  declare -a model_legend=("model19_check3 AWGN Nc=30" "model19_check3 MPP Nc=30" "250227b_test AWGN Nc=10" "250227b_test MPP Nc=10")
fi

# comparsion of models trained with and without --freq_rand and --auxdata, 0 Hz freq offset
if [ $plot == "250412_inf" ]; then
  #run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  #run_model 2504227b_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32
  #run_model 250411 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata
  #run_model 250411 40 200 awgn 1 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata
  #run_model 250411 40 200 awgn 2 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata
  #run_model 250411 40 200 awgn 3 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata
  #run_model 250411b 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32
  #run_model 250412 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata

  model_list='model19_check3_awgn_0Hz 250227b_test_awgn_0Hz 250411_awgn_0Hz 250411b_awgn_0Hz 250412_awgn_0Hz'
  declare -a model_legend=("model19_check3" "250227b_test" "250411 --freq_rand --auxdata" "250411b --freq_rand" "250412 repeat of 250227b")
fi

# compare RADE V1 to 250411 which can handle +/-2 Hz, although all curves tested here at 0 Hz offset
if [ $plot == "250413_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  run_model 250411 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250411 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --g_file g_mpp.f32 --auxdata 

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250411_awgn_0Hz 250411_mpp_0Hz'
  declare -a model_legend=("model19_check3 AWGN Nc=30" "model19_check3 MPP Nc=30" "250411 AWGN Nc=10" "250411 MPP Nc=10")
fi

# 250411 at different freq offsets
if [ $plot == "250413a_inf" ]; then
  run_model 250411 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250411 40 200 awgn 2 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250411 40 200 awgn -2 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250411 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --g_file g_mpp.f32 --auxdata 
  run_model 250411 40 200 mpp 2 --cp 0.004 --time_offset -16 --correct_time_offset -32 --g_file g_mpp.f32 --auxdata 
  run_model 250411 40 200 mpp -2 --cp 0.004 --time_offset -16 --correct_time_offset -32 --g_file g_mpp.f32 --auxdata 

  model_list='250411_awgn_0Hz 250411_awgn_2Hz 250411_awgn_-2Hz 250411_mpp_0Hz 250411_mpp_2Hz 250411_mpp_-2Hz'
  declare -a model_legend=("250411 AWGN 0 Hz" "250411 AWGN 2 Hz" "250411 AWGN -2 Hz" "250411 MPP 0 Hz" "250411 MPP 2 Hz" "250411 MPP -2 Hz")
fi

# Basic AWGN test of frame step 2 models
if [ $plot == "250416_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model 250411 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250413_test 20 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 
  run_model 250416_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 

  model_list='model19_check3_awgn_0Hz 250411_awgn_0Hz 250413_test_awgn_0Hz 250416_test_awgn_0Hz'
  declare -a model_legend=("model19_check3 AWGN fs=4 d=80 Nc=30" "250411 AWGN fs=4 d=40 Nc=10" "250413_test AWGN fs=2 d=20 Nc=10" \
                           "250416_test AWGN fs=2 d=40 Nc=20 start=-3dB")
fi

# compare RADE V1 to 250415, poor MPP results as expected as not trained correctly.
if [ $plot == "250416b_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  run_model 250415_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 
  run_model 250415_test 40 200 mpp  0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 --g_file g_mpp.f32 

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250415_test_awgn_0Hz 250415_test_mpp_0Hz'
  declare -a model_legend=("model19_check3 AWGN  fs=4 d=80 Nc=30" "model19_check3 MPP  fs=4 d=80 Nc=30" "250415 AWGN fs=2 d=40 Nc=20" "250415 MPP fs=2 d=40 Nc=20")
fi

# compare RADE V1 to framestep 2 250416 (poor MPP) and framestep 8 250416a (poor AWNG & MPP)
if [ $plot == "250416a_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  run_model 250416_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 
  run_model 250416a_test 80 200 awgn  0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 8
  run_model 250416_test 40 200 mpp  0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 --g_file g_mpp.f32 
  run_model 250416a_test 80 200 mpp  0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 8 --g_file g_mpp.f32 

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250416_test_awgn_0Hz 250416_test_mpp_0Hz 250416a_test_awgn_0Hz 250416a_test_mpp_0Hz'
  declare -a model_legend=("model19_check3 AWGN fs=4 d=80 Nc=30" "model19_check3 MPP fs=4 d=80 Nc=30" "250416 AWGN fs=2 d=40 Nc=20" \
                           "250416 MPP fs=2 d=40 Nc=20" "250416a AWGN fs=8 d=80 Nc=10" "250416a MPP fs=8 d=80 Nc=10" )
fi

# compare RADE V1 to 250413: framestep 2,d=20,Nc=10 and 250413: framestep 2,d=40,Nc=20
if [ $plot == "250417_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  run_model 250413_test 20 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 
  run_model 250413_test 20 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 --g_file g_mpp.f32
  run_model 250416_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 
  run_model 250416_test 40 200 mpp  0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --frames_per_step 2 --g_file g_mpp.f32 

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250413_test_awgn_0Hz 250413_test_mpp_0Hz 250416_test_awgn_0Hz 250416_test_mpp_0Hz'
  declare -a model_legend=("model19_check3 AWGN fs=4 d=80 Nc=30" "model19_check3 MPP fs=4 d=80 Nc=30" \
                           "250413 AWGN fs=2 d=20 Nc=10" "250413 MPP fs=2 d=20 Nc=10" \
                           "250416 AWGN fs=2 d=40 Nc=20" "250416 MPP fs=2 d=40 Nc=20")
fi

# compare RADE V1 to framestep 4,d=20,Nc=10 250417 (240411 repeat with frame step arg)
if [ $plot == "250417a_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  run_model 250417_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250417_test 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --g_file g_mpp.f32
  run_model 250417a_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250417a_test 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --g_file g_mpp.f32

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250417_test_awgn_0Hz 250417_test_mpp_0Hz 250417a_test_awgn_0Hz 250417a_test_mpp_0Hz'
  declare -a model_legend=("model19_check3 AWGN fs=4 d=80 Nc=30" "model19_check3 MPP fs=4 d=80 Nc=30" \
                           "250417 AWGN fs=4 d=40 Nc=10" "250417 MPP fs=4 d=40 Nc=10" \
                           "250417a AWGN fs=4 d=40 Nc=10" "250417a MPP fs=4 d=40 Nc=10")
fi

# compare RADE V1 to fs=4,Nc=10 250417 to fs=4, Nc=20 250506 (SE 0) & 250506a (SE -3)
if [ $plot == "250506_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  run_model 250417_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250417_test 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --g_file g_mpp.f32
  run_model 250506 80 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250506 80 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --g_file g_mpp.f32
  run_model 250506a 80 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250506a 80 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --g_file g_mpp.f32

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250417_test_awgn_0Hz 250417_test_mpp_0Hz 250506a_awgn_0Hz 250506a_mpp_0Hz 250506_awgn_0Hz 250506_mpp_0Hz'
  declare -a model_legend=("model19_check3 AWGN fs=4 d=80 Nc=30" "model19_check3 MPP d=80 Nc=30" \
                           "250417 AWGN fs=4 d=40 Nc=10 SE 0" "250417 MPP d=40 Nc=10 SE 0" \
                           "250506a AWGN d=80 Nc=20 SE -3" "250506a MPP d=80 Nc=20 SE -3" \
                           "250506 AWGN d=80 Nc=20 SE 0" "250506 MPP d=80 Nc=20 SE 0")
fi

if [ $plot == "250508_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  run_model 250417a_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250417a_test 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --g_file g_mpp.f32
  run_model 250417_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250417_test 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --g_file g_mpp.f32
  run_model 250508_test 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata 
  run_model 250508_test 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -32 --auxdata --g_file g_mpp.f32

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250417_test_awgn_0Hz 250417_test_mpp_0Hz 250417a_test_awgn_0Hz 250417a_test_mpp_0Hz 250508_test_awgn_0Hz 250508_test_mpp_0Hz'
  declare -a model_legend=("model19_check3 AWGN fs=4 d=80 Nc=30" "model19_check3 MPP d=80 Nc=30" \
                           "250417 AWGN fs=4 d=40 Nc=10 SE 0" "250417 MPP d=40 Nc=10 SE 0" \
                           "250417a AWGN fs=4 d=40 Nc=10 SE 3" "250417a MPP d=40 Nc=10 SE 3" \
                           "250508 AWGN fs=4 d=40 Nc=10 SE 6" "250508 MPP d=40 Nc=10 SE 6")
fi

# 250515 is the Nc=10 SE 3 waveform we have been using for ML sync experiments, 250707 has tx BPG/clippers in loop (--txpbf), but doesn't 
# support CP
if [ $plot == "250708_inf" ]; then
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --g_file g_mpp.f32
  run_model 250515 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata 
  run_model 250515 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --g_file g_mpp.f32
  run_model 250707 40 200 awgn 0 --txbpf --auxdata 
  run_model 250707 40 200 mpp 0 --txbpf --auxdata --g_file g_mpp.f32

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250515_awgn_0Hz 250515_mpp_0Hz 250707_awgn_0Hz 250707_mpp_0Hz'
  declare -a model_legend=("model19_check3 AWGN fs=4 d=80 Nc=30" "model19_check3 MPP d=80 Nc=30" \
                           "250515 AWGN fs=4 d=40 Nc=10 SE 3" "250515 MPP d=40 Nc=10 SE 3" \
                           "250707 AWGN fs=4 d=40 Nc=10 SE 3" "250707 MPP d=40 Nc=10 SE 3")
fi

set -x
# With simulation of SSB BPF, which affects PAPR
if [ $plot == "250716_inf" ]; then
  # RADE V1 as run OTA today
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --ssb_bpf
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --ssb_bpf --g_file g_mpp.f32

  # RADE V1 with no pilots (and hence no EQ) to illustrate target performance with ML EQ
  run_model model19_check3 80 100 awgn_np 0 --tanh_clipper --cp 0.004  --auxdata --ssb_bpf

  # Where we've landed with RADE V2 to date - Nc=10 SE=6 use single tanh clipper, no SSB filter in training
  run_model 250717 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --tanh --auxdata --ssb_bpf
  run_model 250717 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --tanh --auxdata --ssb_bpf --g_file g_mpp.f32

  # perf jump with w1_dec=128
  run_model 250719 40 200 awgn 0 --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --tanh --auxdata --w1_dec 128 --ssb_bpf
  run_model 250719 40 200 mpp 0 --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --tanh --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32

  # using bottleneck 2, SE 9: PAPR 10dB, but loss versus SNR impressive
  run_model 250721b 40 200 awgn 0 --bottleneck 2 --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --tanh --auxdata --w1_dec 128 --ssb_bpf 
  run_model 250721b 40 200 mpp 0  --bottleneck 2 --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --tanh --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32

  # using peak in loss function rather than bottleneck activation function
  run_model 250723 56 200 awgn 0 --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf 
  run_model 250723 56 200 mpp 0  --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32

  # repeat of 250723
  run_model 250724 56 200 awgn 0 --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf 
  run_model 250724 56 200 mpp 0  --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32
 
  # --ssb_bpf in training loop
  run_model 250725 56 200 awgn 0 --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf 
  run_model 250725 56 200 mpp 0  --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32

  # --ssb_bpf in training loop
  run_model 250726 56 200 awgn 0 --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf 
  run_model 250726 56 200 mpp 0  --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32

  model_list='model19_check3_awgn_0Hz model19_check3_mpp_0Hz 250725_awgn_0Hz 250725_mpp_0Hz'
  declare -a model_legend=("b+-;RADE V1 AWGN Nc=30;" "bo--;RADE V1 MPP Nc=30;" \
                           "g+-;250725 AWGN Nc=14;" "go--;250725 MPP Nc=14;")
fi

# Plot curves to explore integeration of JMV adasmooth FT estimator
if [ $plot == "251113_inf" ]; then
  # RADE V1 as run OTA today
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --ssb_bpf
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --ssb_bpf --g_file g_mpp.f32

  run_model_rx2 250725 251002_mpp_16k_ft 250725_ml_sync 56 200 awgn
  # put inf stage loss in col 2	
  echo "x=load('250725_awgn_loss_SNR3k.txt'); x(:,2)=x(:,4); save -ascii 250725_awgn_inf_loss_SNR3k.txt x" | octave-cli -qf

  run_model_rx2 250725 251002_mpp_16k_ft 250725_ml_sync 56 200 mpp --g_file g_mpp.f32
  # put inf stage loss in col 2	
  echo "x=load('250725_mpp_loss_SNR3k.txt'); x(:,2)=x(:,4); save -ascii 250725_mpp_inf_loss_SNR3k.txt x" | octave-cli -qf

  model_list='model19_check3_awgn model19_check3_mpp 250725_awgn_inf 250725_mpp_inf 250725_awgn 250725_mpp'
  declare -a model_legend=("b+-;RADE V1 AWGN;" "bo--;RADE V1 MPP;" \
                           "r+-;250725 AWGN Genie;" "ro--;250725 MPP Genie;" \
            						   "g+-;250725 AWGN FT;" "go--;250725 MPP FT;")
fi

# Jan 26 timing corner case - train model that can handle a wider Nj
if [ $plot == "260127_inf" ]; then
  # RADE V1 as run OTA today
  run_model model19_check3 80 100 awgn 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --ssb_bpf
  run_model model19_check3 80 100 mpp 0 --tanh_clipper --cp 0.004 --time_offset -16 --auxdata --pilots --pilot_eq --eq_ls --ssb_bpf --g_file g_mpp.f32

  run_model 250725 56 200 awgn 0 --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf 
  run_model 250725 56 200 mpp 0  --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32

  run_model 260127 56 200 awgn 0 --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf 
  run_model 260127 56 200 mpp 0  --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32

  run_model 260128b 56 200 awgn 0 --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf 
  run_model 260128b 56 200 mpp 0  --bottleneck 0 --peak --cp 0.004 --time_offset -16 --correct_time_offset -16 --auxdata --w1_dec 128 --ssb_bpf --g_file g_mpp.f32

  model_list='model19_check3_awgn model19_check3_mpp 250725_awgn_0Hz 250725_mpp_0Hz 260127_awgn_0Hz  260127_mpp_0Hz 260128b_awgn_0Hz  260128b_mpp_0Hz '
  declare -a model_legend=("b+-;RADE V1 AWGN;" "bo--;RADE V1 MPP;" \
                           "r+-;250725 AWGN Genie;" "ro--;250725 MPP Genie;" \
  					               "g+-;260127 AWGN Genie;" "go--;260127 MPP Genie;"
          						     "c+-;260128b AWGN Genie;" "co--;260128b MPP Genie;")
fi

# Generate the plots in PNG and EPS form, file names have suffix of ${plot}
vargs=""
i=0
for model in $model_list
  do
    vargs="${vargs},'${model}_loss_SNR3k.txt','${model_legend[i]}'"
    ((i++))
  done
echo "radae_plots; loss_SNR3k_plot(psnr=0,'${plot}_loss_SNR3k_models',''${vargs}); quit" | octave-cli -qf # PNG
echo "radae_plots; loss_SNR3k_plot(psnr=1,'${plot}_loss_PNR3k_models',''${vargs}); quit" | octave-cli -qf # PNG
echo "radae_plots; loss_SNR3k_plot(psnr=1,'','${plot}_loss_PNR3k_models'${vargs}); quit" | octave-cli -qf # EPS

